<?php
$GLOBALS['fc_config'] = array (
  'version' => '5.0.7',
  'sound' => 
  array (
    'pan' => 0,
    'volume' => 75,
    'muteAll' => false,
    'muteRingBell' => true,
    'muteSubmitMessage' => false,
    'muteReceiveMessage' => false,
    'muteOtherUserEnters' => false,
    'muteLeaveRoom' => false,
    'muteRoomOpenClose' => false,
    'muteInitialLogin' => false,
    'muteLogout' => false,
    'muteComboListOpenClose' => false,
    'muteUserBannedBooted' => true,
    'muteInvitationReceived' => false,
    'mutePrivateMessageReceived' => false,
    'muteUserMenuMouseOver' => false,
    'mutePopupWindowOpen' => false,
    'mutePopupWindowCloseMin' => false,
    'muteEnterRoom' => true,
    'mutePressButton' => true,
  ),
  'text' => 
  array (
    'itemToChange' => 
    array (
      'myTextColor' => false,
      'mainChat' => 
      array (
        'presence' => true,
        'fontSize' => 13,
        'fontFamily' => 'Arial',
      ),
      'interfaceElements' => 
      array (
        'presence' => true,
        'fontSize' => 13,
        'fontFamily' => 'Arial',
      ),
      'title' => 
      array (
        'presence' => true,
        'fontSize' => 13,
        'fontFamily' => 'Arial',
      ),
    ),
    'fontSize' => 
    array (
      'itm1' => 9,
      'itm2' => 10,
      'itm3' => 11,
      'itm4' => 12,
      'itm5' => 13,
      'itm6' => 14,
      'itm7' => 16,
      'itm8' => 18,
      'itm0' => 8,
      'itm10' => 21,
      'itm9' => 20,
    ),
    'fontFamily' => 
    array (
      'itm0' => 'Arial',
      'itm3' => 'Verdana',
      'itm4' => 'Georgia',
      'itm1' => 'Times',
      'itm2' => 'Courier',
      'itm5' => 'Arcanum',
      'itm6' => 'Atene',
      'itm7' => 'Avalon',
      'itm8' => 'Babycake',
      'itm9' => 'Blatant',
      'itm10' => 'Bluestone',
      'itm11' => 'Bubblegum',
      'itm12' => 'Casual',
      'itm13' => 'Chocolat',
      'itm14' => 'Chubbycheeks',
      'itm15' => 'Conventionalwisdom',
      'itm16' => 'Desigers',
      'itm17' => 'Digitalstrip',
      'itm18' => 'Eastmarket',
      'itm19' => 'Flowerchild',
      'itm20' => 'Flubber',
      'itm21' => 'Gremlins',
      'itm22' => 'Grinched',
      'itm23' => 'Grusskartengotisch',
      'itm24' => 'Handy',
      'itm25' => 'Hazael',
      'itm26' => 'Heartbreaker',
      'itm27' => 'Helvetica',
      'itm28' => 'Hemihead',
      'itm29' => 'Hero',
      'itm30' => 'Holyempire',
      'itm31' => 'Hotpizza',
      'itm32' => 'Irongate',
      'itm33' => 'Ironman',
      'itm34' => 'Jackson',
      'itm35' => 'Jellybelly',
      'itm36' => 'Jester',
      'itm37' => 'Kabel',
      'itm38' => 'Kathrynshand',
      'itm39' => 'Kelt',
      'itm40' => 'Kidkosmic',
      'itm41' => 'Kids',
      'itm42' => 'Kronika',
      'itm43' => 'Linus',
      'itm44' => 'Lisabel',
      'itm45' => 'Loretta',
      'itm46' => 'Louisetta',
      'itm47' => 'Lucidablackletter',
      'itm48' => 'Lucidabright',
      'itm49' => 'Lynda',
      'itm50' => 'Macintosh',
      'itm51' => 'Magicmedieval',
      'itm52' => 'Magnet',
      'itm53' => 'Makimango',
      'itm54' => 'Mandingo',
      'itm55' => 'Mangatemple',
      'itm56' => 'Margo',
      'itm57' => 'Mattoscript',
      'itm58' => 'Mordred',
      'itm59' => 'Nativealien',
      'itm60' => 'Natural',
      'itm61' => 'Negative',
      'itm62' => 'Ninja',
      'itm63' => 'Nordic',
      'itm64' => 'Oldenglish',
      'itm65' => 'Omegasentry',
      'itm66' => 'Padaloma',
      'itm67' => 'Palatino',
      'itm68' => 'Patricia',
      'itm69' => 'Quark',
      'itm70' => 'Rebeka',
      'itm71' => 'Rodney',
      'itm72' => 'Rosans',
      'itm73' => 'Roserif',
      'itm74' => 'Scoobydoo',
      'itm75' => 'Seadog',
      'itm76' => 'Severina',
      'itm77' => 'Slamming',
      'itm78' => 'Southpark',
      'itm79' => 'Sweetascandy',
      'itm80' => 'Swiss',
      'itm81' => 'Technic',
      'itm82' => 'Terryscript',
      'itm83' => 'Thalia',
      'itm84' => 'Tiffany',
      'itm85' => 'Toftlund',
      'itm86' => 'Transformers',
      'itm87' => 'Trosia',
      'itm88' => 'Underattack',
      'itm89' => 'Unicorn',
      'itm90' => 'Village',
      'itm91' => 'Vitriol',
      'itm92' => 'Vivienne',
      'itm93' => 'Vladimir',
      'itm94' => 'Werewolf',
      'itm95' => 'Western',
      'itm96' => 'Whimsy',
    ),
  ),
  'preloader' => 
  array (
    'text' => 
    array (
      'settings' => 'Loading settings...',
      'smilies' => 'Loading smiles....',
      'mainchat' => 'Loading main chat window...',
      'starting' => 'Starting chat system...',
      'okText' => 'OK',
      'failedText' => 'FAILED',
    ),
    'fontFamily' => 'Verdana',
    'fontSize' => '11',
    'fontColor' => 0x000000,
    'BGColor' => 0xFFFFFF,
    'barColor' => 0x000000,
  ),
  'smiles' => 
  array (
    'smi_smile' => ':) :-)',
    'smi_sad' => ':( :-(',
    'smi_wink' => ';) ;-)',
    'smi_laugh' => ':D :-D',
    'smi_red' => ':red:',
    'smi_tongue' => ':p :-p',
    'smi_ask' => ':? :-?',
    'smi_awe' => ':awe:',
    'smi_baby' => ':baby:',
    'smi_cool' => '8) 8-)',
    'smi_evil' => ':evil:',
    'smi_grin' => ':grin:',
    'smi_heart' => ':heart:',
    'smi_kiss' => ':kiss:',
    'smi_newline' => ':break:',
    'smi_ninja' => ':ninja:',
    'smi_roll' => ':roll:',
    'smi_roll_eyes' => ':rolleyes:',
    'smi_slash' => ':! :-!',
    'smi_sleep' => ':zzz:',
    'smi_weird' => ':weird:',
    'smi_whistle' => ':whistle:',
    'smi_wonder' => '8s',
    'smi_call' => ':call:',
    'smi_cash' => ':cash:',
    'smi_shock' => ':shock:',
    'smi_check' => ':check:',
    'smi_ball' => ':ball:',
    'smi_clap' => ':clap:',
    'smi_cry' => ':cry:',
    'smi_luck' => ':luck:',
    'smi_nono' => ':nono:',
    'smi_punch' => ':Punch:',
    'smi_skull' => ':skull:',
    'smi_yeah' => ':yeah:',
    'smi_yinyang' => ':69:',
    'smi_earth' => ':earth:',
    'smi_huh' => ':huh:',
    'smi_hypno' => ':hypno:',
    'smi_java' => ':java:',
    'smi_no' => ':no:',
    'smi_rain' => ':rain:',
    'smi_rose' => ':rose:',
    'smi_usa' => ':usa:',
    'smi_big_grin' => ':biggrin:',
    'smi_faint' => ':faint:',
    'smi_ill_content' => ':mean:',
    'smi_meow' => ':cat:',
    'smi_thumbs_down' => ':down:',
    'smi_thumbs_up' => ':up:',
    'smi_woof' => ':dog:',
    'smi_beer' => ':beer:',
    'smi_music' => ':music:',
    'smi_reading' => ':read:',
    'smi_word_bubble' => ':speak:',
    'smi_female' => ':female:',
    'smi_female2' => ':ms:',
    'smi_male' => ':male:',
    'smi_male2' => ':mr:',
    'smi_admin' => ':admin:',
    'smi_moderator' => ':mod:',
    'smi_basketball' => ':bball:',
    'smi_bowling' => ':bowl:',
    'smi_cricket' => ':cricket:',
    'smi_football' => ':fball:',
    'smi_golf' => ':golf:',
    'smi_hockey' => ':hockey:',
    'smi_sailing' => ':sail:',
    'smi_soccer' => ':soccer:',
    'smi_tennis' => ':tennis:',
    'smi_AustraliaFlag' => ':au:',
    'smi_Brazil' => ':br:',
    'smi_CanadaFlag' => ':ca:',
    'smi_China' => ':cn:',
    'smi_Spain' => ':es:',
    'smi_European_Union' => ':eu:',
    'smi_France' => ':fr:',
    'smi_Germany' => ':de:',
    'smi_Greece' => ':gr:',
    'smi_IndianFlag' => ':in:',
    'smi_Italy' => ':it:',
    'smi_Japan' => ':jp:',
    'smi_MexicoFlag' => ':mx:',
    'smi_PolandFlag' => ':pl:',
    'smi_PortugalFlag' => ':pt:',
    'smi_Russia' => ':ru:',
    'smi_Sweeden' => ':se:',
    'smi_UkraineFlag' => ':ua:',
    'smi_UK' => ':uk:',
    'smi_US_Map' => ':us:',
  ),
  'avatars' => 
  array (
    'mod_only' => 'smi_admin,smi_moderator',
    'user' => 
    array (
      'male' => 
      array (
        'mainchat' => 
        array (
          'default_value' => 'smi_male',
          'default_state' => false,
          'allow_override' => true,
        ),
        'room' => 
        array (
          'default_value' => 'smi_male',
          'default_state' => true,
          'allow_override' => true,
        ),
      ),
      'female' => 
      array (
        'mainchat' => 
        array (
          'default_value' => 'smi_female',
          'default_state' => false,
          'allow_override' => true,
        ),
        'room' => 
        array (
          'default_value' => 'smi_female',
          'default_state' => true,
          'allow_override' => true,
        ),
      ),
    ),
    'admin' => 
    array (
      'male' => 
      array (
        'mainchat' => 
        array (
          'default_value' => 'smi_admin',
          'default_state' => false,
          'allow_override' => true,
        ),
        'room' => 
        array (
          'default_value' => 'smi_admin',
          'default_state' => true,
          'allow_override' => true,
        ),
      ),
      'female' => 
      array (
        'mainchat' => 
        array (
          'default_value' => 'smi_admin',
          'default_state' => false,
          'allow_override' => true,
        ),
        'room' => 
        array (
          'default_value' => 'smi_admin',
          'default_state' => true,
          'allow_override' => true,
        ),
      ),
    ),
    'moderator' => 
    array (
      'male' => 
      array (
        'mainchat' => 
        array (
          'default_value' => 'smi_moderator',
          'default_state' => false,
          'allow_override' => true,
        ),
        'room' => 
        array (
          'default_value' => 'smi_moderator',
          'default_state' => true,
          'allow_override' => true,
        ),
      ),
      'female' => 
      array (
        'mainchat' => 
        array (
          'default_value' => 'smi_moderator',
          'default_state' => false,
          'allow_override' => true,
        ),
        'room' => 
        array (
          'default_value' => 'smi_moderator',
          'default_state' => true,
          'allow_override' => true,
        ),
      ),
    ),
  ),
  'msgRequestInterval' => 3,
  'autologoutAfter' => 60,
  'filesharing' => 
  array (
    'allowShareRoom' => false,
    'allowShareChat' => false,
    'allowFileExt' => 'zip,rar,jpg,gif,sit,pdf',
    'maxFileSize' => 524288,
    'maxFileHoursLife' => '0.5',
  ),
  'logout' => 
  array (
    'close' => true,
    'redirect' => false,
    'url' => 'http://www.tufat.com/chat.php',
    'window' => '0',
  ),
  'module' => 
  array (
    'anchor' => false,
    'path' => false,
    'stretch' => false,
    'float_x' => false,
    'float_y' => false,
    'float_w' => false,
    'float_h' => false,
    'enabled' => false,
  ),
  'is_paid_chat' => false,
  'membership_amount' => 10,
  'payment_test_mode' => true,
  'paypal_bussiness_email' => 'sales@your_domain.com',
  'payment_currency_type' => 'USD',
  'timeOffset' => 0,
  'msgRequestIntervalAway' => 15,
  'autocloseAfter' => 3600,
  'debug' => false,
  'helpUrl' => 'http://tufat.com/docs/flashchat/index.html',
  'sound_options' => 
  array (
    'RingBell' => 'sounds/tin_can.mp3',
    'LeaveRoom' => 'sounds/door_shut.mp3',
    'OtherUserEnters' => 'sounds/jetsons.mp3',
    'ReceiveMessage' => 'sounds/aol_receive_message.mp3',
    'SubmitMessage' => 'sounds/aol_send_message.mp3',
    'RoomOpenClose' => 'sounds/_default.mp3',
    'InitialLogin' => 'sounds/harp_cord.mp3',
    'Logout' => 'sounds/high_low_chord.mp3',
    'ComboListOpenClose' => 'sounds/mouse_over_6.mp3',
    'UserBannedBooted' => 'sounds/chime.mp3',
    'InvitationReceived' => 'sounds/three_notes.mp3',
    'PrivateMessageReceived' => 'sounds/aol_receive_message.mp3',
    'UserMenuMouseOver' => 'sounds/mouse_over_1.mp3',
    'PopupWindowOpen' => 'sounds/air_swoosh_2.mp3',
    'PopupWindowCloseMin' => 'sounds/mouse_over_2.mp3',
    'EnterRoom' => 'sounds/ta_da.mp3',
    'PressButton' => 'sounds/activate_button.mp3',
  ),
  'cacheType' => '1',
  'cachePath' => '../temp/templates/cache/',
  'cacheFilePrefix' => '2019708250',
  'liveSupportMode' => false,
  'enableSocketServer' => false,
  'avatarbgloading' => 
  array (
    'allowFileExt' => 'jpg,gif,png,swf',
    'maxFileSize' => 524288,
    'maxFileHoursLife' => '744',
  ),
  'javaSocketServer' => false,
  'errorReports' => false,
  'enableBots' => false,
  'bot_ip' => '0.0.0.0',
  'photoloading' => 
  array (
    'allowFileExt' => 'jpg,gif,png',
    'maxFileSize' => 104857,
    'maxFileHoursLife' => '744',
  ),
  'hideSelfPopup' => false,
  'showConfirmation' => false,
  'login' => 
  array (
    'btn' => 'true',
    'title_bar' => 'true',
    'theme' => 'macintosh',
    'width' => 0,
    'height' => 0,
    'username' => 
    array (
      'reg' => 'false',
      'req' => 'false',
      'align' => 'right',
      'x_label' => '',
      'y_label' => '',
      'x_field' => '',
      'y_field' => '',
      'type' => 'text',
      'width' => 150,
    ),
    'password' => 
    array (
      'reg' => 'true',
      'req' => 'false',
      'align' => 'right',
      'x_label' => '',
      'y_label' => '',
      'x_field' => '',
      'y_field' => '',
      'type' => 'password',
      'width' => 150,
    ),
    'lang' => 
    array (
      'align' => 'right',
      'x_label' => '',
      'y_label' => '',
      'x_field' => '',
      'y_field' => '',
    ),
    'title' => 
    array (
      'align' => 'center',
      'x_label' => '',
      'y_label' => '',
      'x_field' => '',
      'y_field' => '',
    ),
  ),
  'labelFormat' => 'AVATAR[USER] TIMESTAMP: ',
  'roomTitleFormat' => 'ROOM_LABEL - USER_COUNT',
  'linebreaktext' => '...',
  'userTitleFormat' => 'AVATAR USER (STATUS)',
  'timeStampFormat' => 'g:i a',
  'loginsPerIP' => 10,
  'disabledIRC' => ',',
  'mods' => ',',
  'modsAdminRestrictions' => ',',
  'base' => '',
  'maxMessageSize' => 500,
  'commands' => 
  array (
    'showIP' => true,
    'userPM' => false,
    'adminPM' => true,
    'maxRooms' => 50,
  ),
  'maxMessageCount' => 100,
  'userListAutoExpand' => false,
  'showLogoutWindow' => false,
  'logoutWindowDisplayTime' => 3,
  'appdata_path' => './appdata/appTime.txt',
  'floodInterval' => 1,
  'botsdata_path' => './appdata/bots.txt',
  'inactivityInterval' => 86400,
  'splashWindow' => false,
  'defaultRoom' => '1',
  'autoremoveAfter' => 30,
  'maxUsersPerRoom' => 50,
  'listOrder' => '0',
  'msgRemoveAfter' => 86400,
  'CMSsystem' => 'statelessCMS',
  'loginUTF8decode' => true,
  'encryptPass' => false,
  'adminPassword' => '4',
  'moderatorPassword' => '5',
  'spyPassword' => '2',
  'auto_motd' => false,
  'auto_topic' => false,
  'backtimeMax' => 5,
  'backMax' => 30,
  'volumeinc' => 5,
  'paninc' => 5,
  'transparencyinc' => 5,
  'defaultTheme' => 'metallic',
  'defaultSkin' => 'default',
  'special_language' => 
  array (
    'itm0' => 'jp,cn',
  ),
  'autounbanAfter' => 36000,
  'defaultLanguage' => 'tr',
  'allowLanguage' => false,
);
?>