<?php $langs = array('ar.php' => '0',
'bg.php' => '1',
'br.php' => '2',
'cn.php' => '3',
'cz.php' => '4',
'da.php' => '5',
'du.php' => '6',
'en.php' => '7',
'fi.php' => '8',
'fr.php' => '9',
'gm.php' => '10',
'gr.php' => '11',
'he.php' => '12',
'hi.php' => '13',
'hr.php' => '14',
'hu.php' => '15',
'id.php' => '16',
'it.php' => '17',
'jp.php' => '18',
'kl.php' => '19',
'lt.php' => '20',
'no.php' => '21',
'pg.php' => '22',
'pl.php' => '23',
'pt.php' => '24',
'ro.php' => '25',
'ru.php' => '26',
'sf.php' => '27',
'si.php' => '28',
'sk.php' => '29',
'sp.php' => '30',
'sv.php' => '31',
'th.php' => '32',
'tr.php' => '33',
'tw.php' => '34',
'ua.php' => '35',

); ?>